### PR TITLE
update  auotfac to 5.1.2,net framewrok to 4.6.1 and

### PR DESCRIPTION
**Pull request by lwqwag**
Prism to 7.2.0.1422

### CODE REVIEW

**Comment by mkoertgen** [comment]
@lwqwag With the current v2.0.0, updating Autofac explicitly to anything >= 5.x breaks in [FinalizeExtension()](https://github.com/hvaring/Prism.Autofac.Mutable.Wpf/blob/master/src/Prism.Autofac.Mutable.Wpf/Ioc/AutofacContainerExtension.cs#L22) because the extension-method `ContainerBuilder.RegisterSource` has moved from `RegistrationExtensions` to `SourceRegistrationExtensions`.

This PR fixes this by recompilation. Accepting the PR and publishing an updated package would allow us to update to a recent Autofac version.

@hvaring Any doubts or other aspects we should discuss? What can we do to help publishing an updated version?

**Comment by hvaring** [comment]
Thanks for this, I'll have a look this weekend.

**Comment by mkoertgen** [comment]
Hi @hvaring, did you have time to look into this?

**Comment by hvaring** [comment]
Sorry this took so long. Merged and published new package (3.0.0).

**Comment by mkoertgen** [comment]
@hvaring Great! Many thanks

**Pull request merged**
